### ISSUE TITLE
Building project with maven does not work

### ISSUE THREAD

**Issue by Zeblote** [ata4/disunity#117]
You don't keep your releases updated so we have to try to build it ourselves. There's no tutorial so I'm assuming I have to run the "mvn package" command found in another issue. Unfortunately, this leads to a compiler error:

![mavenerror](https://cloud.githubusercontent.com/assets/6764788/7230623/ea96fce4-e76f-11e4-84fe-2ebb0d6d1118.jpg)

Is there an error in the project? Am I doing something wrong? Can you update the releases?

**Comment by ata4** [comment]
There's a good reason why I don't upload new releases: the current branch is unstable and untested. I'm currently trying to port some code for Unity 5, which breaks some submodules. Since this is causing troubles for those that compile the most recent commit, I'll revert the recent modifications and continue on a separate branch.
