### ISSUE TITLE
[Question]The import info.ata4.io.lzma.LzmaEncoderProps can't resolved

### ISSUE THREAD

**Issue by UsingtcNower** [ata4/disunity#120]
I try to build from the source code, and encounter this error. I know it is embarrassing, but can anyone tell me where to find the missing class?

**Comment by ata4** [comment]
That isn't embarrassing at all. It looks like you somehow have an older version of my [lzmajio fork](https://github.com/ata4/lzmajio/tree/ata4). Which is strange, because I updated the POM months ago to use the new version and I also don't get this error when building the project. When you open the pom.xml of DisUnity, do you have the following lines?:

        <dependency>
            <groupId>com.github.ata4</groupId>
            <artifactId>lzmajio</artifactId>
            <version>5daa9c59b8</version>
        </dependency>

**Comment by UsingtcNower** [comment]
Thanks a lot. I did reference an older version of lzmajio. After using the latest version, it works well. 
Much appreciate your effort for this great project!
