### ISSUE TITLE
Remove NetBeans files, improve .gitignore

### ISSUE THREAD

**Issue by moshen** [ata4/disunity#99]
I was going to submit this as a PR, but that might mess with your existing development setup... also this probably falls under "suggestions".  Adding something like https://www.gitignore.io/api/java,maven,eclipse,netbeans,jetbrains,vim to your `.gitignore` would help anyone else who may want to contribute.  Also, removing IDE-sentric config like `nbproject` and `build.xml` makes things a little cleaner.

I wrote this under the assumption that this is meant to be a maven build/project.

**Comment by ata4** [comment]
This project was originally created as a NetBeans project using Ant to compile it. The Maven files were committed by contributors, but I want to stay with my build environment for now, because the Maven plugin for NetBeans doesn't really work well from my experiences so far. That's why the project folder is a bit messy right now. I'm also working on a big rewrite for ioutils, so the code is currently uncompilable as well.

I guess I'll try to hide all NetBeans related files and create a working Maven environment while continuing to use Ant personally.

**Comment by moshen** [comment]
That makes sense.  It's pretty easy to chain [maven from ant](http://maven.apache.org/ant-tasks/) (or [the other way around](http://maven.apache.org/plugins/maven-antrun-plugin/)).  I've had mixed experiences using maven integration in Java IDEs (Though, [Intellij](https://www.jetbrains.com/idea/download/) works pretty well).  If all else fails, it's pretty easy to run it from the command line.

By having builds from maven, you can easily automate builds with a continuous integration environment (like [travis](https://travis-ci.org)).

I think [gitignore.io](https://gitignore.io) pulls from [github/gitignore](https://github.com/github/gitignore), FYI.

**Comment by ata4** [comment]
I think I have to contradict my previous statement regarding Maven and NetBeans. After some research and experiments, it turns out that it actually works very well when you stay close to the default Maven workflow. I also figured out how to use the command line version, which is installed together with and used by the NetBeans Maven plugin.

I updated a few repositories already and together with jitpack.io, it's fairly trivial to manage my custom libraries now. I'll try to work with Maven directly from now on and fix the remaining code to get DisUnity working again.

**Comment by lcplpunishment** [comment]
*thumbs up*.. keep up the good work

2015-02-25 11:39 GMT+01:00 ata4 <notifications@github.com>:

**Comment by Syphurith** [comment]
@ata4 I can not build the repo now. [Here](https://gist.github.com/Syphurith/1343c41810ae6e7aa040) is the `mvn install -U` log. Version: ata4/disunity@533bcd623054e0167733905a58091d32694bd905. 
It seems now Jitpack.io doesn't have pom for lzmajio and ioutils. When i tried to access the pom.xml link such as [this](https://jitpack.io/com/github/ata4/ioutils/0.0.0-SNAPSHOT/ioutils-0.0.0-SNAPSHOT.pom) I only got `{"message":"error: Not found","status":"error"}`.

BTW, the `build.xml` tried to include `nbproject/build-impl.xml` which was used to provide the purposed operations for `ant` and was recently removed. I tried `ant` and you can see the result in the log above. *Netbeans project is removed*, and i wonder how can you build it now..

**Comment by ata4** [comment]
I'm currently porting the project to Maven, which can also be opened with NetBeans. Once that is done, the project should be compilable again.

**Comment by Syphurith** [comment]
@ata4 well thanks for the effort. Well wait till you done that.

**Comment by ata4** [comment]
Okay, I ported everything and run a few quick tests. To make sure ioutils is working correct, I'll need to write proper unit tests, but for now, DisUnity should compile again.

**Comment by Syphurith** [comment]
@ata4 OK, thanks for the fix. Build successfully now.
